# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            'OpenNMT'
tagline:          'NMT'
description:      'An open-source neural machine translation system.'
url:              http://harvardnlp.github.io/
baseurl:          /

author:
  name:           'Yoon Kim and HarvardNLP'
  url:            https://twitter.com/harvardnlp


# Custom vars
version:          0.1

github:
  repo:           https://github.com/opennmt/opennmt
